pipeline:
  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t nodejs-base:$${DRONE_COMMIT_SHA} .
    when:
      branch: master
      event: push

  build_app:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t nodejs-base:$${DRONE_COMMIT_SHA} .
    when:
      event: pull_request

  image_to_quay:
    image: docker:18.03.1-ce
    secrets:
      - docker_password
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - bin/image_to_quay.sh
    when:
      branch: master
      event: push

